from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from agent import run_review_analysis_agent
from tools import classify_reviews


SAMPLE_DATA_PATH = Path("data/sample_reviews.csv")
EDGE_CASE_DATA_PATH = Path("data/edge_case_reviews.csv")
EVAL_DATA_PATH = Path("data/labelled_eval_reviews.csv")


st.set_page_config(
    page_title="Amazon Review Analysis Agent",
    page_icon="🛒",
    layout="wide"
)


def load_csv_safely(file_or_path):
    """Load a CSV and normalise rating values when possible."""
    df = pd.read_csv(file_or_path)

    if "rating" in df.columns:
        df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

    return df


def df_to_csv_bytes(df):
    """Convert a dataframe to CSV bytes for Streamlit download buttons."""
    return df.to_csv(index=False).encode("utf-8")


def recommendations_to_df(recommendations):
    """Convert recommendation list to dataframe."""
    if not recommendations:
        return pd.DataFrame(
            columns=["category", "count", "percentage", "recommendation"]
        )

    return pd.DataFrame(recommendations)


def build_markdown_report(result):
    """Build a downloadable Markdown report from agent results."""
    observation = result["observation"]
    decision = result["decision"]
    stats = result["category_statistics"]
    voc_summary = result.get("voc_summary", {})
    recommendations = result["qc_recommendations"]

    report_lines = []

    report_lines.append("# Amazon Review Analysis Agent VOC Report")
    report_lines.append("")
    report_lines.append("## 1. Dataset Observation")
    report_lines.append(f"- Total rows: {observation['total_rows']}")
    report_lines.append(f"- Total columns: {observation['total_columns']}")
    report_lines.append(f"- Missing comment rate: {observation['comment_missing_rate']}%")
    report_lines.append(f"- Low-rating review rate: {observation['low_rating_rate']}%")
    report_lines.append("")

    report_lines.append("## 2. Agent Decision")
    report_lines.append(f"- Analysis focus: {decision['analysis_focus']}")

    if decision["warnings"]:
        report_lines.append("- Warnings:")
        for warning in decision["warnings"]:
            report_lines.append(f"  - {warning}")
    else:
        report_lines.append("- No major data quality warnings detected.")

    report_lines.append("")
    report_lines.append("## 3. Defect Category Statistics")

    if stats is not None and not stats.empty:
        for _, row in stats.iterrows():
            report_lines.append(
                f"- {row['category']}: {int(row['count'])} reviews ({row['percentage']}%)"
            )
    else:
        report_lines.append("- No category statistics available.")

    report_lines.append("")
    report_lines.append("## 4. VOC Theme Summary")

    theme_summary = voc_summary.get("theme_summary", pd.DataFrame())
    if theme_summary is not None and not theme_summary.empty:
        for _, row in theme_summary.iterrows():
            report_lines.append(
                f"- {row['voc_theme']}: {int(row['count'])} reviews ({row['percentage']}%)"
            )
    else:
        report_lines.append("- No VOC theme summary available.")

    report_lines.append("")
    report_lines.append("## 5. Severity Summary")

    severity_summary = voc_summary.get("severity_summary", pd.DataFrame())
    if severity_summary is not None and not severity_summary.empty:
        for _, row in severity_summary.iterrows():
            report_lines.append(
                f"- {row['voc_severity']}: {int(row['count'])} reviews ({row['percentage']}%)"
            )
    else:
        report_lines.append("- No severity summary available.")

    report_lines.append("")
    report_lines.append("## 6. QC Recommendations")

    if recommendations:
        for item in recommendations:
            report_lines.append(f"### {item['category']}")
            report_lines.append(f"- Count: {item['count']} reviews")
            report_lines.append(f"- Share: {item['percentage']}%")
            report_lines.append(f"- Recommended action: {item['recommendation']}")
            report_lines.append("")
    else:
        report_lines.append("- No defect-specific QC recommendations generated.")

    report_lines.append("")
    report_lines.append("## 7. Safety and Reliability")
    report_lines.append(
        "- Numerical statistics are computed by Python rather than generated by an LLM."
    )
    report_lines.append(
        "- Review labels are selected from a predefined taxonomy."
    )
    report_lines.append(
        "- Unknown or vague reviews are marked as unknown."
    )
    report_lines.append(
        "- Edge-case datasets can trigger warnings for manual review."
    )
    report_lines.append(
        "- VOC themes, severity, pain points, and root-cause hypotheses are generated from controlled rule mappings."
    )
    report_lines.append(
        "- Evaluation uses taxonomy-aligned scoring to avoid unfairly penalising semantically close labels."
    )

    return "\n".join(report_lines)


def normalize_human_label(label):
    """
    Map detailed human labels into the agent's predefined taxonomy.

    The evaluation dataset may use more fine-grained labels than the agent.
    This function aligns human labels to the agent taxonomy before scoring.
    """
    if pd.isna(label):
        return "unknown"

    label = str(label).strip()

    label_map = {
        # Charging / power related
        "charging_failure": "charging_failure",
        "charging_base_failure": "charging_base_failure",
        "charging_pin_contact_issue": "charging_pin_contact_issue",
        "missing_charge_indicator": "charging_failure",
        "charger_compatibility": "charging_failure",
        "battery_life_short": "battery_life_issue",
        "battery_life_issue": "battery_life_issue",
        "positive_battery": "positive_feedback",

        # Reliability
        "stopped_working": "stopped_working",
        "early_failure": "stopped_working",
        "broken_unit": "stopped_working",

        # Grinding / coarseness / jamming
        "grinding_power_issue": "grinding_power_issue",
        "grinding_coarseness_issue": "coarseness_adjustment_issue",
        "coarseness_adjustment_issue": "coarseness_adjustment_issue",
        "grinding_stuck_issue": "salt_or_pepper_jamming",
        "jamming_issue": "salt_or_pepper_jamming",
        "positive_grinding": "positive_feedback",
        "positive_performance": "positive_feedback",

        # Jamming / mess / refill
        "salt_or_pepper_jamming": "salt_or_pepper_jamming",
        "messy_dispensing": "messy_dispensing",
        "button_placement_issue": "messy_dispensing",
        "small_capacity_or_refill_issue": "small_capacity_or_refill_issue",
        "capacity_refill_issue": "small_capacity_or_refill_issue",

        # Build / surface
        "material_or_build_quality_issue": "material_or_build_quality_issue",
        "build_quality_issue": "material_or_build_quality_issue",
        "surface_stain_issue": "surface_stain_issue",
        "finish_staining_issue": "surface_stain_issue",

        # Positive feedback
        "positive_feedback": "positive_feedback",
        "positive_design": "positive_feedback",
        "positive_usability": "positive_feedback",
        "accessibility_positive": "positive_feedback",

        # Customer service
        "customer_service_positive": "customer_service_positive",

        # Unknown / vague
        "unknown": "unknown",
        "vague": "unknown",
    }

    return label_map.get(label, label)


def get_acceptable_agent_categories(normalized_label):
    """
    Define acceptable agent categories for taxonomy-aligned evaluation.

    Some labels are semantically close. For example, a charging pin issue is a
    specific form of charging base/contact failure. This avoids unfairly
    penalising the agent for choosing a more specific or adjacent defect label.
    """
    acceptable_map = {
        "charging_failure": {
            "charging_failure",
            "charging_base_failure",
            "charging_pin_contact_issue",
            "battery_life_issue",
            "stopped_working",
        },
        "charging_base_failure": {
            "charging_base_failure",
            "charging_pin_contact_issue",
            "charging_failure",
        },
        "charging_pin_contact_issue": {
            "charging_pin_contact_issue",
            "charging_base_failure",
            "charging_failure",
        },
        "battery_life_issue": {
            "battery_life_issue",
            "charging_failure",
        },
        "stopped_working": {
            "stopped_working",
            "charging_failure",
            "charging_base_failure",
        },
        "grinding_power_issue": {
            "grinding_power_issue",
            "coarseness_adjustment_issue",
            "salt_or_pepper_jamming",
        },
        "coarseness_adjustment_issue": {
            "coarseness_adjustment_issue",
            "grinding_power_issue",
        },
        "salt_or_pepper_jamming": {
            "salt_or_pepper_jamming",
            "grinding_power_issue",
        },
        "messy_dispensing": {
            "messy_dispensing",
        },
        "small_capacity_or_refill_issue": {
            "small_capacity_or_refill_issue",
        },
        "material_or_build_quality_issue": {
            "material_or_build_quality_issue",
        },
        "surface_stain_issue": {
            "surface_stain_issue",
        },
        "positive_feedback": {
            "positive_feedback",
            "customer_service_positive",
        },
        "customer_service_positive": {
            "customer_service_positive",
        },
        "unknown": {
            "unknown",
        },
    }

    return acceptable_map.get(normalized_label, {normalized_label})


def run_labelled_evaluation():
    """Run taxonomy-aligned evaluation on labelled_eval_reviews.csv."""
    eval_df = load_csv_safely(EVAL_DATA_PATH)

    if "human_label" not in eval_df.columns:
        raise ValueError("The evaluation CSV must contain a 'human_label' column.")

    if "review_title" not in eval_df.columns:
        eval_df["review_title"] = ""

    if "review_id" not in eval_df.columns:
        eval_df["review_id"] = [f"E{i + 1:03d}" for i in range(len(eval_df))]

    classified_eval = classify_reviews(eval_df)

    classified_eval["normalized_human_label"] = classified_eval["human_label"].apply(
        normalize_human_label
    )

    classified_eval["accepted_agent_categories"] = classified_eval[
        "normalized_human_label"
    ].apply(lambda label: sorted(get_acceptable_agent_categories(label)))

    classified_eval["is_correct"] = classified_eval.apply(
        lambda row: row["agent_category"]
        in get_acceptable_agent_categories(row["normalized_human_label"]),
        axis=1,
    )

    classified_eval["evaluation_type"] = "taxonomy_aligned"

    total = len(classified_eval)
    correct = int(classified_eval["is_correct"].sum())
    accuracy = correct / total if total > 0 else 0

    return classified_eval, total, correct, accuracy


def plot_horizontal_bar(dataframe, label_col, value_col, title):
    """Create a readable horizontal bar chart."""
    if dataframe is None or dataframe.empty:
        st.info("No statistics available for charting.")
        return

    chart_df = dataframe.sort_values(value_col, ascending=True)

    fig_height = max(4, len(chart_df) * 0.45)
    fig, ax = plt.subplots(figsize=(10, fig_height))
    ax.barh(chart_df[label_col], chart_df[value_col])
    ax.set_xlabel("Review count")
    ax.set_ylabel(label_col)
    ax.set_title(title)

    st.pyplot(fig, clear_figure=True)


st.title("🛒 Amazon Review Analysis Agent")

st.write(
    "This prototype analyses Amazon product reviews by observing a CSV dataset, "
    "deciding an analysis path, classifying review issues, computing VOC-level insights, "
    "and recommending quality-control actions."
)

st.sidebar.title("Agent Controls")

input_source = st.sidebar.radio(
    "Choose input source",
    [
        "Upload CSV",
        "Use sample_reviews.csv",
        "Use edge_case_reviews.csv",
    ]
)

df = None
source_name = None

if input_source == "Upload CSV":
    uploaded_file = st.sidebar.file_uploader("Upload a CSV file", type=["csv"])

    if uploaded_file is not None:
        df = load_csv_safely(uploaded_file)
        source_name = uploaded_file.name

elif input_source == "Use sample_reviews.csv":
    df = load_csv_safely(SAMPLE_DATA_PATH)
    source_name = "sample_reviews.csv"

elif input_source == "Use edge_case_reviews.csv":
    df = load_csv_safely(EDGE_CASE_DATA_PATH)
    source_name = "edge_case_reviews.csv"


st.sidebar.markdown("---")
st.sidebar.write("### What the agent does")
st.sidebar.write(
    """
    1. Observes the dataset  
    2. Checks data quality  
    3. Decides analysis focus  
    4. Classifies review issues  
    5. Builds VOC themes  
    6. Infers severity and pain points  
    7. Generates QC actions  
    8. Supports evaluation  
    """
)

if "analysis_result" not in st.session_state:
    st.session_state.analysis_result = None

if "current_source_name" not in st.session_state:
    st.session_state.current_source_name = None

if source_name != st.session_state.current_source_name:
    st.session_state.analysis_result = None
    st.session_state.current_source_name = source_name


if df is None:
    st.info(
        "Please upload a CSV file or choose one of the sample datasets from the sidebar."
    )
    st.stop()


st.caption(f"Current dataset: **{source_name}**")

with st.expander("Dataset Preview", expanded=True):
    st.dataframe(df.head(20), use_container_width=True)

    col_a, col_b, col_c = st.columns(3)

    with col_a:
        st.metric("Rows", len(df))

    with col_b:
        st.metric("Columns", len(df.columns))

    with col_c:
        st.metric("Missing Values", int(df.isna().sum().sum()))

    st.write("Detected columns:")
    st.write(list(df.columns))


run_button = st.button("🚀 Run Agent Analysis", type="primary")

if run_button:
    with st.spinner(
        "Agent is observing, deciding, classifying, building VOC insights, and generating recommendations..."
    ):
        st.session_state.analysis_result = run_review_analysis_agent(df)


result = st.session_state.analysis_result

if result is None:
    st.info("Click **Run Agent Analysis** to start.")
    st.stop()


observation = result["observation"]
decision = result["decision"]
classified_reviews = result["classified_reviews"]
voc_reviews = result.get("voc_reviews")
category_statistics = result["category_statistics"]
voc_summary = result.get("voc_summary", {})
qc_recommendations = result["qc_recommendations"]


tab_dashboard, tab_voc, tab_classification, tab_recommendations, tab_evidence, tab_evaluation = st.tabs(
    [
        "📊 Dashboard",
        "🧭 VOC Analysis",
        "🏷️ Classification",
        "🛠️ QC Recommendations",
        "🔎 Evidence Explorer",
        "✅ Evaluation",
    ]
)


with tab_dashboard:
    st.subheader("Agent Observation")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Rows", observation["total_rows"])

    with col2:
        st.metric("Columns", observation["total_columns"])

    with col3:
        st.metric("Missing Comments", f"{observation['comment_missing_rate']}%")

    with col4:
        st.metric("Low-Rating Reviews", f"{observation['low_rating_rate']}%")

    st.subheader("Agent Decision")
    st.write(f"Analysis focus: **{decision['analysis_focus']}**")

    if decision["warnings"]:
        for warning in decision["warnings"]:
            st.warning(warning)
    else:
        st.success("No major data quality warnings detected.")

    if category_statistics is not None and not category_statistics.empty:
        st.subheader("Defect Category Distribution")
        st.dataframe(category_statistics.head(12), use_container_width=True)
        plot_horizontal_bar(
            category_statistics,
            "category",
            "count",
            "Review Issue Category Distribution",
        )

    if classified_reviews is not None:
        markdown_report = build_markdown_report(result)

        st.download_button(
            label="⬇️ Download VOC Markdown Report",
            data=markdown_report.encode("utf-8"),
            file_name="amazon_review_voc_report.md",
            mime="text/markdown",
        )


with tab_voc:
    st.subheader("VOC Analysis Dashboard")

    if voc_reviews is None or voc_reviews.empty:
        st.info("No VOC-level review data available.")
    else:
        theme_summary = voc_summary.get("theme_summary", pd.DataFrame())
        sub_issue_summary = voc_summary.get("sub_issue_summary", pd.DataFrame())
        severity_summary = voc_summary.get("severity_summary", pd.DataFrame())
        sentiment_summary = voc_summary.get("sentiment_summary", pd.DataFrame())

        st.markdown("### VOC Theme Summary")
        st.dataframe(theme_summary, use_container_width=True)
        plot_horizontal_bar(
            theme_summary,
            "voc_theme",
            "count",
            "VOC Theme Distribution",
        )

        st.markdown("### Severity Summary")
        col_sev_1, col_sev_2 = st.columns([1, 1])

        with col_sev_1:
            st.dataframe(severity_summary, use_container_width=True)

        with col_sev_2:
            plot_horizontal_bar(
                severity_summary,
                "voc_severity",
                "count",
                "VOC Severity Distribution",
            )

        st.markdown("### Sentiment Summary")
        st.dataframe(sentiment_summary, use_container_width=True)

        st.markdown("### VOC Sub-Issue Summary")
        st.dataframe(sub_issue_summary, use_container_width=True, height=350)

        st.download_button(
            label="⬇️ Download VOC-Enriched Reviews CSV",
            data=df_to_csv_bytes(voc_reviews),
            file_name="voc_enriched_reviews.csv",
            mime="text/csv",
        )


with tab_classification:
    st.subheader("Review Classification Results")

    if voc_reviews is None:
        st.error(
            "The uploaded CSV is missing required columns. Please check the dataset format."
        )
    else:
        all_categories = sorted(voc_reviews["agent_category"].dropna().unique())

        selected_categories = st.multiselect(
            "Filter by agent category",
            options=all_categories,
            default=all_categories,
        )

        all_themes = sorted(voc_reviews["voc_theme"].dropna().unique())

        selected_themes = st.multiselect(
            "Filter by VOC theme",
            options=all_themes,
            default=all_themes,
        )

        all_severities = sorted(voc_reviews["voc_severity"].dropna().unique())

        selected_severities = st.multiselect(
            "Filter by severity",
            options=all_severities,
            default=all_severities,
        )

        filtered_reviews = voc_reviews.copy()

        if selected_categories:
            filtered_reviews = filtered_reviews[
                filtered_reviews["agent_category"].isin(selected_categories)
            ]

        if selected_themes:
            filtered_reviews = filtered_reviews[
                filtered_reviews["voc_theme"].isin(selected_themes)
            ]

        if selected_severities:
            filtered_reviews = filtered_reviews[
                filtered_reviews["voc_severity"].isin(selected_severities)
            ]

        if "rating" in filtered_reviews.columns:
            rating_values = pd.to_numeric(filtered_reviews["rating"], errors="coerce")

            if rating_values.notna().any():
                min_rating = int(rating_values.min())
                max_rating = int(rating_values.max())

                selected_rating_range = st.slider(
                    "Filter by rating",
                    min_value=min_rating,
                    max_value=max_rating,
                    value=(min_rating, max_rating),
                )

                filtered_reviews = filtered_reviews[
                    pd.to_numeric(filtered_reviews["rating"], errors="coerce").between(
                        selected_rating_range[0],
                        selected_rating_range[1],
                    )
                ]

        display_columns = [
            "review_id",
            "rating",
            "review_title",
            "customer_comment",
            "agent_category",
            "agent_confidence",
            "agent_evidence",
            "voc_theme",
            "voc_sub_issue",
            "voc_sentiment",
            "voc_severity",
            "customer_pain_point",
            "business_impact",
        ]

        available_display_columns = [
            col for col in display_columns if col in filtered_reviews.columns
        ]

        st.write(f"Showing **{len(filtered_reviews)}** classified reviews.")
        st.dataframe(
            filtered_reviews[available_display_columns],
            use_container_width=True,
            height=520,
        )

        st.download_button(
            label="⬇️ Download VOC Classification CSV",
            data=df_to_csv_bytes(voc_reviews),
            file_name="voc_classified_reviews.csv",
            mime="text/csv",
        )


with tab_recommendations:
    st.subheader("Category Statistics")

    if category_statistics is None or category_statistics.empty:
        st.info("No category statistics available.")
    else:
        st.dataframe(category_statistics, use_container_width=True)
        plot_horizontal_bar(
            category_statistics,
            "category",
            "count",
            "Defect Category Distribution",
        )

    st.subheader("Quality-Control Recommendations")

    recommendation_df = recommendations_to_df(qc_recommendations)

    if recommendation_df.empty:
        st.info("No defect-specific QC recommendations were generated.")
    else:
        st.dataframe(recommendation_df, use_container_width=True)

        for item in qc_recommendations:
            with st.container(border=True):
                st.markdown(f"### `{item['category']}`")
                st.write(f"**Count:** {item['count']} reviews")
                st.write(f"**Share:** {item['percentage']}%")
                st.write(f"**Recommended action:** {item['recommendation']}")

        st.download_button(
            label="⬇️ Download QC Recommendations CSV",
            data=df_to_csv_bytes(recommendation_df),
            file_name="qc_recommendations.csv",
            mime="text/csv",
        )


with tab_evidence:
    st.subheader("VOC Evidence Explorer")

    if voc_reviews is None or voc_reviews.empty:
        st.info("No VOC evidence available.")
    else:
        categories = sorted(voc_reviews["agent_category"].dropna().unique())

        selected_category = st.selectbox(
            "Choose a category to inspect evidence",
            categories,
        )

        evidence_df = voc_reviews[
            voc_reviews["agent_category"] == selected_category
        ]

        st.write(f"Evidence examples for: **{selected_category}**")

        display_columns = [
            "review_id",
            "rating",
            "review_title",
            "customer_comment",
            "agent_evidence",
            "agent_confidence",
            "voc_theme",
            "voc_sub_issue",
            "voc_severity",
            "customer_pain_point",
            "root_cause_hypothesis",
            "business_impact",
        ]

        available_display_columns = [
            col for col in display_columns if col in evidence_df.columns
        ]

        st.dataframe(
            evidence_df[available_display_columns],
            use_container_width=True,
            height=450,
        )

        if len(evidence_df) > 0:
            st.markdown("### Example VOC Interpretation")
            first_row = evidence_df.iloc[0]

            st.write(
                f"**Customer comment:** {first_row.get('customer_comment', 'No comment available.')}"
            )
            st.write(f"**VOC theme:** {first_row.get('voc_theme', '')}")
            st.write(f"**Sub-issue:** {first_row.get('voc_sub_issue', '')}")
            st.write(f"**Pain point:** {first_row.get('customer_pain_point', '')}")
            st.write(
                f"**Root-cause hypothesis:** {first_row.get('root_cause_hypothesis', '')}"
            )
            st.write(f"**Business impact:** {first_row.get('business_impact', '')}")


with tab_evaluation:
    st.subheader("Labelled Evaluation")

    st.write(
        "This evaluates the rule-based classifier against a small human-labelled dataset. "
        "Human labels are first normalised into the agent's predefined taxonomy, and "
        "semantically close defect labels are treated as acceptable matches."
    )

    if st.button("Run Evaluation on labelled_eval_reviews.csv"):
        try:
            classified_eval, total, correct, accuracy = run_labelled_evaluation()

            col_eval_1, col_eval_2, col_eval_3 = st.columns(3)

            with col_eval_1:
                st.metric("Total Examples", total)

            with col_eval_2:
                st.metric("Correct Predictions", correct)

            with col_eval_3:
                st.metric("Taxonomy-Aligned Accuracy", f"{accuracy:.2%}")

            incorrect_cases = classified_eval[classified_eval["is_correct"] == False]

            st.subheader("Incorrect Cases")

            if incorrect_cases.empty:
                st.success("No incorrect cases found.")
            else:
                display_columns = [
                    "review_id",
                    "customer_comment",
                    "human_label",
                    "normalized_human_label",
                    "accepted_agent_categories",
                    "agent_category",
                    "agent_confidence",
                    "agent_evidence",
                    "evaluation_type",
                ]

                available_display_columns = [
                    col for col in display_columns if col in incorrect_cases.columns
                ]

                st.dataframe(
                    incorrect_cases[available_display_columns],
                    use_container_width=True,
                    height=450,
                )

            st.download_button(
                label="⬇️ Download Evaluation Results CSV",
                data=df_to_csv_bytes(classified_eval),
                file_name="evaluation_results.csv",
                mime="text/csv",
            )

        except Exception as error:
            st.error(f"Evaluation failed: {error}")